#!/bin/bash
#SBATCH --partition=test
#SBATCH -o %j.out
#SBATCH -e %j.err
#SBATCH --time=00:20:00
#SBATCH --time-min=00:05:00
#SBATCH --ntasks=8

python ../optimize.py --caldir ../ --exepath ~/nanofase/bin/main --test parallel --maxworkers 8